// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cloudtrust/common-service/v2/security (interfaces: AuthorizationDBReader,RoleBasedAuthorizationDBReader)
//
// Generated by this command:
//
//	mockgen --build_flags=--mod=mod -destination=./mock/authentication_db_reader.go -package=mock -mock_names=AuthorizationDBReader=AuthorizationDBReader,RoleBasedAuthorizationDBReader=RoleBasedAuthorizationDBReader github.com/cloudtrust/common-service/v2/security AuthorizationDBReader,RoleBasedAuthorizationDBReader
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	configuration "github.com/cloudtrust/common-service/v2/configuration"
	gomock "go.uber.org/mock/gomock"
)

// AuthorizationDBReader is a mock of AuthorizationDBReader interface.
type AuthorizationDBReader struct {
	ctrl     *gomock.Controller
	recorder *AuthorizationDBReaderMockRecorder
	isgomock struct{}
}

// AuthorizationDBReaderMockRecorder is the mock recorder for AuthorizationDBReader.
type AuthorizationDBReaderMockRecorder struct {
	mock *AuthorizationDBReader
}

// NewAuthorizationDBReader creates a new mock instance.
func NewAuthorizationDBReader(ctrl *gomock.Controller) *AuthorizationDBReader {
	mock := &AuthorizationDBReader{ctrl: ctrl}
	mock.recorder = &AuthorizationDBReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *AuthorizationDBReader) EXPECT() *AuthorizationDBReaderMockRecorder {
	return m.recorder
}

// GetAuthorizations mocks base method.
func (m *AuthorizationDBReader) GetAuthorizations(arg0 context.Context) ([]configuration.Authorization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthorizations", arg0)
	ret0, _ := ret[0].([]configuration.Authorization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuthorizations indicates an expected call of GetAuthorizations.
func (mr *AuthorizationDBReaderMockRecorder) GetAuthorizations(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthorizations", reflect.TypeOf((*AuthorizationDBReader)(nil).GetAuthorizations), arg0)
}

// RoleBasedAuthorizationDBReader is a mock of RoleBasedAuthorizationDBReader interface.
type RoleBasedAuthorizationDBReader struct {
	ctrl     *gomock.Controller
	recorder *RoleBasedAuthorizationDBReaderMockRecorder
	isgomock struct{}
}

// RoleBasedAuthorizationDBReaderMockRecorder is the mock recorder for RoleBasedAuthorizationDBReader.
type RoleBasedAuthorizationDBReaderMockRecorder struct {
	mock *RoleBasedAuthorizationDBReader
}

// NewRoleBasedAuthorizationDBReader creates a new mock instance.
func NewRoleBasedAuthorizationDBReader(ctrl *gomock.Controller) *RoleBasedAuthorizationDBReader {
	mock := &RoleBasedAuthorizationDBReader{ctrl: ctrl}
	mock.recorder = &RoleBasedAuthorizationDBReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *RoleBasedAuthorizationDBReader) EXPECT() *RoleBasedAuthorizationDBReaderMockRecorder {
	return m.recorder
}

// GetAdminConfiguration mocks base method.
func (m *RoleBasedAuthorizationDBReader) GetAdminConfiguration(ctx context.Context, realmID string) (configuration.RealmAdminConfiguration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdminConfiguration", ctx, realmID)
	ret0, _ := ret[0].(configuration.RealmAdminConfiguration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdminConfiguration indicates an expected call of GetAdminConfiguration.
func (mr *RoleBasedAuthorizationDBReaderMockRecorder) GetAdminConfiguration(ctx, realmID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdminConfiguration", reflect.TypeOf((*RoleBasedAuthorizationDBReader)(nil).GetAdminConfiguration), ctx, realmID)
}
