// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cloudtrust/common-service/v2/security (interfaces: KeycloakClient,RoleBasedKeycloakClient)
//
// Generated by this command:
//
//	mockgen --build_flags=--mod=mod -destination=./mock/keycloak_client.go -package=mock -mock_names=KeycloakClient=KeycloakClient,RoleBasedKeycloakClient=RoleBasedKeycloakClient github.com/cloudtrust/common-service/v2/security KeycloakClient,RoleBasedKeycloakClient
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// KeycloakClient is a mock of KeycloakClient interface.
type KeycloakClient struct {
	ctrl     *gomock.Controller
	recorder *KeycloakClientMockRecorder
	isgomock struct{}
}

// KeycloakClientMockRecorder is the mock recorder for KeycloakClient.
type KeycloakClientMockRecorder struct {
	mock *KeycloakClient
}

// NewKeycloakClient creates a new mock instance.
func NewKeycloakClient(ctrl *gomock.Controller) *KeycloakClient {
	mock := &KeycloakClient{ctrl: ctrl}
	mock.recorder = &KeycloakClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *KeycloakClient) EXPECT() *KeycloakClientMockRecorder {
	return m.recorder
}

// GetGroupName mocks base method.
func (m *KeycloakClient) GetGroupName(ctx context.Context, accessToken, realmName, groupID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupName", ctx, accessToken, realmName, groupID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupName indicates an expected call of GetGroupName.
func (mr *KeycloakClientMockRecorder) GetGroupName(ctx, accessToken, realmName, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupName", reflect.TypeOf((*KeycloakClient)(nil).GetGroupName), ctx, accessToken, realmName, groupID)
}

// GetGroupNamesOfUser mocks base method.
func (m *KeycloakClient) GetGroupNamesOfUser(ctx context.Context, accessToken, realmName, userID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupNamesOfUser", ctx, accessToken, realmName, userID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupNamesOfUser indicates an expected call of GetGroupNamesOfUser.
func (mr *KeycloakClientMockRecorder) GetGroupNamesOfUser(ctx, accessToken, realmName, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupNamesOfUser", reflect.TypeOf((*KeycloakClient)(nil).GetGroupNamesOfUser), ctx, accessToken, realmName, userID)
}

// RoleBasedKeycloakClient is a mock of RoleBasedKeycloakClient interface.
type RoleBasedKeycloakClient struct {
	ctrl     *gomock.Controller
	recorder *RoleBasedKeycloakClientMockRecorder
	isgomock struct{}
}

// RoleBasedKeycloakClientMockRecorder is the mock recorder for RoleBasedKeycloakClient.
type RoleBasedKeycloakClientMockRecorder struct {
	mock *RoleBasedKeycloakClient
}

// NewRoleBasedKeycloakClient creates a new mock instance.
func NewRoleBasedKeycloakClient(ctrl *gomock.Controller) *RoleBasedKeycloakClient {
	mock := &RoleBasedKeycloakClient{ctrl: ctrl}
	mock.recorder = &RoleBasedKeycloakClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *RoleBasedKeycloakClient) EXPECT() *RoleBasedKeycloakClientMockRecorder {
	return m.recorder
}

// GetRoleNamesOfUser mocks base method.
func (m *RoleBasedKeycloakClient) GetRoleNamesOfUser(ctx context.Context, accessToken, realmName, userID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoleNamesOfUser", ctx, accessToken, realmName, userID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoleNamesOfUser indicates an expected call of GetRoleNamesOfUser.
func (mr *RoleBasedKeycloakClientMockRecorder) GetRoleNamesOfUser(ctx, accessToken, realmName, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoleNamesOfUser", reflect.TypeOf((*RoleBasedKeycloakClient)(nil).GetRoleNamesOfUser), ctx, accessToken, realmName, userID)
}
