// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cloudtrust/common-service/v2/database (interfaces: DbTransactionIntf)
//
// Generated by this command:
//
//	mockgen --build_flags=--mod=mod -destination=./mock/database.go -package=mock -mock_names=DbTransactionIntf=DbTransactionIntf github.com/cloudtrust/common-service/v2/database DbTransactionIntf
//

// Package mock is a generated GoMock package.
package mock

import (
	sql "database/sql"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// DbTransactionIntf is a mock of DbTransactionIntf interface.
type DbTransactionIntf struct {
	ctrl     *gomock.Controller
	recorder *DbTransactionIntfMockRecorder
	isgomock struct{}
}

// DbTransactionIntfMockRecorder is the mock recorder for DbTransactionIntf.
type DbTransactionIntfMockRecorder struct {
	mock *DbTransactionIntf
}

// NewDbTransactionIntf creates a new mock instance.
func NewDbTransactionIntf(ctrl *gomock.Controller) *DbTransactionIntf {
	mock := &DbTransactionIntf{ctrl: ctrl}
	mock.recorder = &DbTransactionIntfMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *DbTransactionIntf) EXPECT() *DbTransactionIntfMockRecorder {
	return m.recorder
}

// Commit mocks base method.
func (m *DbTransactionIntf) Commit() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit")
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *DbTransactionIntfMockRecorder) Commit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*DbTransactionIntf)(nil).Commit))
}

// Exec mocks base method.
func (m *DbTransactionIntf) Exec(query string, args ...any) (sql.Result, error) {
	m.ctrl.T.Helper()
	varargs := []any{query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exec", varargs...)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *DbTransactionIntfMockRecorder) Exec(query any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*DbTransactionIntf)(nil).Exec), varargs...)
}

// Query mocks base method.
func (m *DbTransactionIntf) Query(query string, args ...any) (*sql.Rows, error) {
	m.ctrl.T.Helper()
	varargs := []any{query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Query", varargs...)
	ret0, _ := ret[0].(*sql.Rows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *DbTransactionIntfMockRecorder) Query(query any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*DbTransactionIntf)(nil).Query), varargs...)
}

// QueryRow mocks base method.
func (m *DbTransactionIntf) QueryRow(query string, args ...any) *sql.Row {
	m.ctrl.T.Helper()
	varargs := []any{query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRow", varargs...)
	ret0, _ := ret[0].(*sql.Row)
	return ret0
}

// QueryRow indicates an expected call of QueryRow.
func (mr *DbTransactionIntfMockRecorder) QueryRow(query any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRow", reflect.TypeOf((*DbTransactionIntf)(nil).QueryRow), varargs...)
}

// Rollback mocks base method.
func (m *DbTransactionIntf) Rollback() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rollback")
	ret0, _ := ret[0].(error)
	return ret0
}

// Rollback indicates an expected call of Rollback.
func (mr *DbTransactionIntfMockRecorder) Rollback() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*DbTransactionIntf)(nil).Rollback))
}
