// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cloudtrust/common-service/v2/healthcheck (interfaces: KafkaConsumer)
//
// Generated by this command:
//
//	mockgen --build_flags=--mod=mod -destination=./mock/kafka.go -package=mock -mock_names=KafkaConsumer=KafkaConsumer github.com/cloudtrust/common-service/v2/healthcheck KafkaConsumer
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// KafkaConsumer is a mock of KafkaConsumer interface.
type KafkaConsumer struct {
	ctrl     *gomock.Controller
	recorder *KafkaConsumerMockRecorder
	isgomock struct{}
}

// KafkaConsumerMockRecorder is the mock recorder for KafkaConsumer.
type KafkaConsumerMockRecorder struct {
	mock *KafkaConsumer
}

// NewKafkaConsumer creates a new mock instance.
func NewKafkaConsumer(ctrl *gomock.Controller) *KafkaConsumer {
	mock := &KafkaConsumer{ctrl: ctrl}
	mock.recorder = &KafkaConsumerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *KafkaConsumer) EXPECT() *KafkaConsumerMockRecorder {
	return m.recorder
}

// IsLive mocks base method.
func (m *KafkaConsumer) IsLive() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsLive")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsLive indicates an expected call of IsLive.
func (mr *KafkaConsumerMockRecorder) IsLive() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsLive", reflect.TypeOf((*KafkaConsumer)(nil).IsLive))
}
