// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fb

import "strconv"

type EventSource int8

const (
	EventSourceKC_EVENT       EventSource = 0
	EventSourceKC_ADMIN_EVENT EventSource = 1
	EventSourceCT_EVENT       EventSource = 2
)

var EnumNamesEventSource = map[EventSource]string{
	EventSourceKC_EVENT:       "KC_EVENT",
	EventSourceKC_ADMIN_EVENT: "KC_ADMIN_EVENT",
	EventSourceCT_EVENT:       "CT_EVENT",
}

var EnumValuesEventSource = map[string]EventSource{
	"KC_EVENT":       EventSourceKC_EVENT,
	"KC_ADMIN_EVENT": EventSourceKC_ADMIN_EVENT,
	"CT_EVENT":       EventSourceCT_EVENT,
}

func (v EventSource) String() string {
	if s, ok := EnumNamesEventSource[v]; ok {
		return s
	}
	return "EventSource(" + strconv.FormatInt(int64(v), 10) + ")"
}
