// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fb

import "strconv"

type OperationType int8

const (
	OperationTypeCREATE         OperationType = 0
	OperationTypeUPDATE         OperationType = 1
	OperationTypeDELETE         OperationType = 2
	OperationTypeACTION         OperationType = 3
	OperationTypeNOT_APPLICABLE OperationType = 4
)

var EnumNamesOperationType = map[OperationType]string{
	OperationTypeCREATE:         "CREATE",
	OperationTypeUPDATE:         "UPDATE",
	OperationTypeDELETE:         "DELETE",
	OperationTypeACTION:         "ACTION",
	OperationTypeNOT_APPLICABLE: "NOT_APPLICABLE",
}

var EnumValuesOperationType = map[string]OperationType{
	"CREATE":         OperationTypeCREATE,
	"UPDATE":         OperationTypeUPDATE,
	"DELETE":         OperationTypeDELETE,
	"ACTION":         OperationTypeACTION,
	"NOT_APPLICABLE": OperationTypeNOT_APPLICABLE,
}

func (v OperationType) String() string {
	if s, ok := EnumNamesOperationType[v]; ok {
		return s
	}
	return "OperationType(" + strconv.FormatInt(int64(v), 10) + ")"
}
