// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fb

import "strconv"

type ResourceType int8

const (
	ResourceTypeREALM                         ResourceType = 0
	ResourceTypeREALM_ROLE                    ResourceType = 1
	ResourceTypeREALM_ROLE_MAPPING            ResourceType = 2
	ResourceTypeREALM_SCOPE_MAPPING           ResourceType = 3
	ResourceTypeAUTH_FLOW                     ResourceType = 4
	ResourceTypeAUTH_EXECUTION_FLOW           ResourceType = 5
	ResourceTypeAUTH_EXECUTION                ResourceType = 6
	ResourceTypeAUTHENTICATOR_CONFIG          ResourceType = 7
	ResourceTypeREQUIRED_ACTION               ResourceType = 8
	ResourceTypeIDENTITY_PROVIDER             ResourceType = 9
	ResourceTypeIDENTITY_PROVIDER_MAPPER      ResourceType = 10
	ResourceTypePROTOCOL_MAPPER               ResourceType = 11
	ResourceTypeUSER                          ResourceType = 12
	ResourceTypeUSER_LOGIN_FAILURE            ResourceType = 13
	ResourceTypeUSER_SESSION                  ResourceType = 14
	ResourceTypeUSER_FEDERATION_PROVIDER      ResourceType = 15
	ResourceTypeUSER_FEDERATION_MAPPER        ResourceType = 16
	ResourceTypeGROUP                         ResourceType = 17
	ResourceTypeGROUP_MEMBERSHIP              ResourceType = 18
	ResourceTypeCLIENT                        ResourceType = 19
	ResourceTypeCLIENT_INITIAL_ACCESS_MODEL   ResourceType = 20
	ResourceTypeCLIENT_ROLE                   ResourceType = 21
	ResourceTypeCLIENT_ROLE_MAPPING           ResourceType = 22
	ResourceTypeCLIENT_SCOPE                  ResourceType = 23
	ResourceTypeCLIENT_SCOPE_MAPPING          ResourceType = 24
	ResourceTypeCLUSTER_NODE                  ResourceType = 25
	ResourceTypeCOMPONENT                     ResourceType = 26
	ResourceTypeAUTHORIZATION_RESOURCE_SERVER ResourceType = 27
	ResourceTypeAUTHORIZATION_RESOURCE        ResourceType = 28
	ResourceTypeAUTHORIZATION_SCOPE           ResourceType = 29
	ResourceTypeAUTHORIZATION_POLICY          ResourceType = 30
	ResourceTypeUNKNOWN                       ResourceType = 31
	ResourceTypeNOT_APPLICABLE                ResourceType = 32
)

var EnumNamesResourceType = map[ResourceType]string{
	ResourceTypeREALM:                         "REALM",
	ResourceTypeREALM_ROLE:                    "REALM_ROLE",
	ResourceTypeREALM_ROLE_MAPPING:            "REALM_ROLE_MAPPING",
	ResourceTypeREALM_SCOPE_MAPPING:           "REALM_SCOPE_MAPPING",
	ResourceTypeAUTH_FLOW:                     "AUTH_FLOW",
	ResourceTypeAUTH_EXECUTION_FLOW:           "AUTH_EXECUTION_FLOW",
	ResourceTypeAUTH_EXECUTION:                "AUTH_EXECUTION",
	ResourceTypeAUTHENTICATOR_CONFIG:          "AUTHENTICATOR_CONFIG",
	ResourceTypeREQUIRED_ACTION:               "REQUIRED_ACTION",
	ResourceTypeIDENTITY_PROVIDER:             "IDENTITY_PROVIDER",
	ResourceTypeIDENTITY_PROVIDER_MAPPER:      "IDENTITY_PROVIDER_MAPPER",
	ResourceTypePROTOCOL_MAPPER:               "PROTOCOL_MAPPER",
	ResourceTypeUSER:                          "USER",
	ResourceTypeUSER_LOGIN_FAILURE:            "USER_LOGIN_FAILURE",
	ResourceTypeUSER_SESSION:                  "USER_SESSION",
	ResourceTypeUSER_FEDERATION_PROVIDER:      "USER_FEDERATION_PROVIDER",
	ResourceTypeUSER_FEDERATION_MAPPER:        "USER_FEDERATION_MAPPER",
	ResourceTypeGROUP:                         "GROUP",
	ResourceTypeGROUP_MEMBERSHIP:              "GROUP_MEMBERSHIP",
	ResourceTypeCLIENT:                        "CLIENT",
	ResourceTypeCLIENT_INITIAL_ACCESS_MODEL:   "CLIENT_INITIAL_ACCESS_MODEL",
	ResourceTypeCLIENT_ROLE:                   "CLIENT_ROLE",
	ResourceTypeCLIENT_ROLE_MAPPING:           "CLIENT_ROLE_MAPPING",
	ResourceTypeCLIENT_SCOPE:                  "CLIENT_SCOPE",
	ResourceTypeCLIENT_SCOPE_MAPPING:          "CLIENT_SCOPE_MAPPING",
	ResourceTypeCLUSTER_NODE:                  "CLUSTER_NODE",
	ResourceTypeCOMPONENT:                     "COMPONENT",
	ResourceTypeAUTHORIZATION_RESOURCE_SERVER: "AUTHORIZATION_RESOURCE_SERVER",
	ResourceTypeAUTHORIZATION_RESOURCE:        "AUTHORIZATION_RESOURCE",
	ResourceTypeAUTHORIZATION_SCOPE:           "AUTHORIZATION_SCOPE",
	ResourceTypeAUTHORIZATION_POLICY:          "AUTHORIZATION_POLICY",
	ResourceTypeUNKNOWN:                       "UNKNOWN",
	ResourceTypeNOT_APPLICABLE:                "NOT_APPLICABLE",
}

var EnumValuesResourceType = map[string]ResourceType{
	"REALM":                         ResourceTypeREALM,
	"REALM_ROLE":                    ResourceTypeREALM_ROLE,
	"REALM_ROLE_MAPPING":            ResourceTypeREALM_ROLE_MAPPING,
	"REALM_SCOPE_MAPPING":           ResourceTypeREALM_SCOPE_MAPPING,
	"AUTH_FLOW":                     ResourceTypeAUTH_FLOW,
	"AUTH_EXECUTION_FLOW":           ResourceTypeAUTH_EXECUTION_FLOW,
	"AUTH_EXECUTION":                ResourceTypeAUTH_EXECUTION,
	"AUTHENTICATOR_CONFIG":          ResourceTypeAUTHENTICATOR_CONFIG,
	"REQUIRED_ACTION":               ResourceTypeREQUIRED_ACTION,
	"IDENTITY_PROVIDER":             ResourceTypeIDENTITY_PROVIDER,
	"IDENTITY_PROVIDER_MAPPER":      ResourceTypeIDENTITY_PROVIDER_MAPPER,
	"PROTOCOL_MAPPER":               ResourceTypePROTOCOL_MAPPER,
	"USER":                          ResourceTypeUSER,
	"USER_LOGIN_FAILURE":            ResourceTypeUSER_LOGIN_FAILURE,
	"USER_SESSION":                  ResourceTypeUSER_SESSION,
	"USER_FEDERATION_PROVIDER":      ResourceTypeUSER_FEDERATION_PROVIDER,
	"USER_FEDERATION_MAPPER":        ResourceTypeUSER_FEDERATION_MAPPER,
	"GROUP":                         ResourceTypeGROUP,
	"GROUP_MEMBERSHIP":              ResourceTypeGROUP_MEMBERSHIP,
	"CLIENT":                        ResourceTypeCLIENT,
	"CLIENT_INITIAL_ACCESS_MODEL":   ResourceTypeCLIENT_INITIAL_ACCESS_MODEL,
	"CLIENT_ROLE":                   ResourceTypeCLIENT_ROLE,
	"CLIENT_ROLE_MAPPING":           ResourceTypeCLIENT_ROLE_MAPPING,
	"CLIENT_SCOPE":                  ResourceTypeCLIENT_SCOPE,
	"CLIENT_SCOPE_MAPPING":          ResourceTypeCLIENT_SCOPE_MAPPING,
	"CLUSTER_NODE":                  ResourceTypeCLUSTER_NODE,
	"COMPONENT":                     ResourceTypeCOMPONENT,
	"AUTHORIZATION_RESOURCE_SERVER": ResourceTypeAUTHORIZATION_RESOURCE_SERVER,
	"AUTHORIZATION_RESOURCE":        ResourceTypeAUTHORIZATION_RESOURCE,
	"AUTHORIZATION_SCOPE":           ResourceTypeAUTHORIZATION_SCOPE,
	"AUTHORIZATION_POLICY":          ResourceTypeAUTHORIZATION_POLICY,
	"UNKNOWN":                       ResourceTypeUNKNOWN,
	"NOT_APPLICABLE":                ResourceTypeNOT_APPLICABLE,
}

func (v ResourceType) String() string {
	if s, ok := EnumNamesResourceType[v]; ok {
		return s
	}
	return "ResourceType(" + strconv.FormatInt(int64(v), 10) + ")"
}
